### ISSUE TITLE
Does not seem to work with Constraints and AutoLayout

### ISSUE THREAD

**Issue by CrazyGoose** [ziligy/JGFlipMenu#3]
The key seems to be this line of code in JGFlipMenuItem.swift:

```
private func setup() {
      menuItemFrame = CGRect(x: 0, y: 0, width: self.frame.size.width, height: self.frame.size.height)
```

But I have no idea how to adjust it to make it work.  

![screen shot 2015-07-08 at 6 31 22 pm](https://cloud.githubusercontent.com/assets/3039813/8583942/a44c8fc4-259f-11e5-8938-fa9ebea73c8e.png)

**Comment by ziligy** [comment]
Take a look at the example, it uses constraints. Does your storyboard function correctly before assigning the menu classes?
